### PR TITLE
migrated to null safety

### PR DESCRIPTION
**Pull request by csells**

### CODE REVIEW

**Comment by comigor** [comment]
Hey @csells, thanks for the PR!
I'll re-setup this repo pipeline and then rebase/accept it!

**Comment by csells** [comment]
cool! when do you think you'll publish to pub.dev?

**Comment by comigor** [comment]
I've fixed the CI, it's already published as [0.2.0-nullsafety.0](https://pub.dev/packages/d20/versions/0.2.0-nullsafety.0)! :)

**Comment by csells** [comment]
perfect. thanks!

any idea when you'll move it from pre-release to release?

**Comment by comigor** [comment]
I'll review some classes that could be non-nullable and ship a non-pre-release version!

**Pull request merged**
